### PR TITLE
godep save against terraform 0.6.15

### PR DESCRIPTION
**Pull request by rubbish**
**godep save against terraform 0.6.15**

Part of https://github.com/Banno/terraform-provider-marathon/pull/28

### CODE REVIEW

**Comment by rubbish** [comment]
retest this please

**Comment by rubbish** [comment]
retest this please

**Comment by rubbish** [comment]
> *** Test killed: ran too long (10m0s).

👎

**Comment by rubbish** [comment]
fixed by adding a `-timeout 20m` to the `go test` command.

**Comment by rubbish** [comment]
retest this please

**Comment by sherzberg** [comment]
screenshot 2016-05-11 09 43 57

**Pull request merged**
